### ISSUE TITLE
Change the footer links on doc

### ISSUE THREAD

**Issue by materazu** [caporl/website#14]
Need this links : 
- install the cli
- create first project
- project structure
- demo

And in community : 
- add github issues
- add caporl cli page

We need another column, with link to money contributors, same as footer of website

**Comment by giuliano2014** [comment]
@materazu 
Pourrais-tu me donner les liens pour add github issues et add caporl cli page ?!
Merci d'avance :)

**Comment by materazu** [comment]
Lien issues sur cli et lien vers le page projet github du cli

Le lun. 25 févr. 2019 à 12:36, Giuliano Furgol <notifications@github.com> a
écrit :
