### ISSUE TITLE
Responsive version

### ISSUE THREAD

**Issue by materazu** [caporl/website#16]
We need to provide a responsive version for the homepage, doc is ok.

**Comment by giuliano2014** [comment]
@materazu 
Dois-je me fier à la version mobile de Zeplin ?!
https://app.zeplin.io/project/5c6277a7386ad09b280ad9a7/screen/5c6eaec93f0470408bf66be0
Et faire un point avec Melody, si besoin :)

**Comment by materazu** [comment]
Vois en direct avec melo

Le lun. 25 févr. 2019 à 11:20, Giuliano Furgol <notifications@github.com> a
écrit :
