### ISSUE TITLE
Link on docs (hat) have a bad redirect

### ISSUE THREAD

**Issue by materazu** [caporl/website#19]
Now, with translation, the link on doc redirect to https://caporl.io/en/ instead of https://caporl.io/

**Comment by giuliano2014** [comment]
@materazu 
Je pense qu'il faudra faire une redirection mais à voir avec toi.
Suite à l'internationalisation de la doc, ce lien est dynamic selon la langue dans laquelle nous sommes.
Aucune info sur la doc de Docusaurus et en ligne pour overrider cela.

**Comment by materazu** [comment]
Ok c'est ce que je pensais, à la limite on se mets le react router et on
gère ça avec ?

Le lun. 25 févr. 2019 à 11:00, Giuliano Furgol <notifications@github.com> a
écrit :

**Comment by giuliano2014** [comment]
@materazu 
Ça roule, je vois si c'est jouable.
